### ISSUE TITLE
기초 config 셋팅 수정

### ISSUE THREAD

**Issue by visualkhh** [geoseong/simple-boot-front#1]
기초 config 셋팅수정
    
## 1. raw-loader로 순수 파일읽기 처리
- import css from "raw-loader!./app.css"
- import html from 'raw-loader!./app.html'

## 2. tsconfig.json 수정(가비지제거)
 - "types": ["node"]

## 3. typescript type 추가
 - index.d.ts
    declare module '*.html' {
        const content: string
        export default content
    }
    declare module '*.css' {
        const content: string
        export default content
    }

**Comment by geoseong** [comment]
각자 내용 수정은 어디 경로에서 수정이 된 것일까요?

**Comment by visualkhh** [comment]
1. raw-loader로 순수 파일읽기 처리
 - src/features/index.ts
   - import html from "raw-loader!./index.html";
 - src/layouts/App.ts
   - import css from 'raw-loader!./app.css'
   - import html from 'raw-loader!./app.html'

2. tsconfig.json 
 - /tsconfig.json
   - "types": ["node"]
 
3. index.d.ts 파일생성
 - src/index.d.ts
 - 내용
declare module '*.html' {
    const content: string
    export default content
}
declare module '*.css' {
    const content: string
    export default content
}
